
spring:
    application:
        name: bibliotecaapi
    datasource:
        url: jdbc:mysql://localhost:3306/biblioteca?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=UTC&useSSL=false
        username: fatec
        password: F@tec2022
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
server:
    servlet:
        contextPath: /api
    port: 8090  